### ISSUE TITLE
dependency bcrypt returns 404 when downloading

### ISSUE THREAD

**Issue by rafaduka** [robmclarty/knex-express-project-sample#1]
**Error:**
`node-pre-gyp ERR! Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v1.0.3/bcrypt_lib-v1.0.3-node-v64-win32-x64.tar.gz`

Temporary Solution: I have upgrade to 3.0.0
```
"dependencies": {
    "bcrypt": "^3.0.0",
    "body-parser": "^1.18.2",
    "express": "^4.16.3",
    "knex": "^0.14.4",
    "pg": "^7.4.1"
  }
```

**Comment by robmclarty** [comment]
Sorry for the delayed response. Seems like there was an issue with npm v5 involving node-pre-gyp which affected this (https://github.com/npm/npm/issues/16728 & https://github.com/kelektiv/node.bcrypt.js/issues/509) but subsequent versions of npm (e.g., >= 5.3) seems to have fixed this. 

That said, it's probably a good idea to upgrade :D I'll work on this a bit more in the near future and do so.

Thanks for the headsup!
