### ISSUE TITLE
No return statement.

### ISSUE THREAD

**Issue by aryyya** [robmclarty/knex-express-project-sample#2]
https://github.com/robmclarty/knex-express-project-sample/blob/08304f5fb183a9068f730bdbd70e804ea433ec73/server/models/user.js#L50

Is there supposed to be a return statement here? Since this is an arrow function with a curly braced body, the function would return `undefined` to the caller.

**Comment by robmclarty** [comment]
ooph, I've been so busy this year! sorry for the hugely delayed reply, but yes, I think you're right! I'll look at this more closely this weekend :)

**Comment by robmclarty** [comment]
Now returning the result of the `knex.select()` statement.
