### ISSUE TITLE
Undefined variable.

### ISSUE THREAD

**Issue by aryyya** [robmclarty/knex-express-project-sample#3]
https://github.com/robmclarty/knex-express-project-sample/blob/08304f5fb183a9068f730bdbd70e804ea433ec73/server/helpers/model-guts.js#L38

`users` here should be `results`.

I've found this codebase to be an incredibly useful reference. This is my second issue of a minor code error that I've noticed as I've gone through it. If it is unwanted, I will stop opening these.

**Comment by robmclarty** [comment]
Nice catch @aryyya. And thank you! Definitely appreciated!

Sorry I've been so negligent. Just been overwhelmed at work. I'll get on this shortly!

**Comment by robmclarty** [comment]
Ok, just updated this. Thanks!
