### ISSUE TITLE
Undefined binding(s) detected

### ISSUE THREAD

**Issue by app-god** [robmclarty/knex-express-project-sample#6]
I git cloned the repo and it's giving me this error when I send POST data (username and password) to /register:

> Undefined binding(s) detected when compiling SELECT. Undefined column(s): [username] query: select `id`, `username`, `email`, `updated_at`, `created_at` from `users` where `username` = ?

When I access the database on the sqlite3 CLI, I get the expected results:

`sqlite> SELECT username from users;`
`admin`
`first-user`

Is there any more info I can provide to help? Thanks

**Comment by app-god** [comment]
Seems like it was an issue with Postman, a program I'm using to send and receive HTTP requests.

**Comment by robmclarty** [comment]
Hey there. Sorry been kind of not paying attention to all my Github stuff during this ridiculous year :P Glad you were able to figure it out!

I'm planning to do another pass through this project in this month to update the dependencies and apply some new refactors I've been using in some of my latest projects that I think would help. Let me know if you have any other questions :)
